# Generated by Django 4.0.4 on 2022-04-29 13:55

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('tombo', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Tombo')),
                ('descricao_abreviada', models.CharField(blank=True, max_length=255, verbose_name='Descrição Abreviada')),
                ('aquisicao', models.CharField(blank=True, max_length=255, verbose_name='Aquisição')),
                ('empenho', models.CharField(blank=True, max_length=255, verbose_name='Empenho')),
                ('processo', models.CharField(blank=True, max_length=255, verbose_name='Processo')),
                ('termo', models.CharField(blank=True, max_length=255, verbose_name='Termo')),
                ('tipo_termo', models.CharField(blank=True, max_length=255, verbose_name='Tipo Termo')),
                ('recebedor', models.CharField(blank=True, max_length=255, verbose_name='Recebedor')),
                ('responsavel', models.CharField(blank=True, max_length=255, verbose_name='Responsável')),
                ('inservivel', models.CharField(blank=True, max_length=255, verbose_name='Inservível')),
                ('observacao', models.CharField(blank=True, max_length=255, verbose_name='Observação')),
                ('grupo', models.CharField(blank=True, max_length=255, verbose_name='Grupo')),
                ('localidade', models.CharField(blank=True, max_length=255, verbose_name='Localidade')),
                ('valor', models.CharField(blank=True, max_length=255, verbose_name='Valor')),
            ],
            options={
                'verbose_name_plural': 'Tombos',
                'ordering': ['tombo'],
            },
            managers=[
                ('equipamento', django.db.models.manager.Manager()),
            ],
        ),
    ]
