# Generated by Django 4.0.4 on 2022-05-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AplicativoInventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, verbose_name='Valor'),
        ),
    ]
